# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

events:
    name: Events
    slug: events
    singular_name: Event
    singular_slug: event
    behaves_like: categories
    multiple: false
    options: [ Freitag, Samstag ]

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ News, Brauch, 'Gschichtä vom Brunnä', 'Unsere Kollegen', 'Fragen & Antworten' ]
    listing_template: blogs.twig
